sudo: false
language: python
python:
  - "3.6"
compiler:
  - clang
  - gcc
cache:
  - apt
os:
  - osx
  - linux
addons:
  apt:
    packages:
    - build-essential
    - libtool
    - libpcap0.8
    - libpcap-dev
    - jq
    - golang
before_script:
  - ./bootstrap.sh
  - cmake . && make
  - ./buildgo.sh
script:
  - ./benchmark.py
  - cat ./results.json | jq .
